# Generated by Django 4.1.1 on 2023-03-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationID', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('maxTemperature', models.IntegerField()),
                ('minTemperature', models.IntegerField()),
                ('precipitation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationID', models.CharField(max_length=20)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('numberOfRecords', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationID', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('avgMaxTemperature', models.IntegerField()),
                ('avgMinTemperature', models.IntegerField()),
                ('totalPrecipitation', models.IntegerField()),
            ],
        ),
    ]
