# Generated by Django 4.1.1 on 2023-03-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherlog',
            name='endTime',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='weatherlog',
            name='startTime',
            field=models.CharField(max_length=50),
        ),
    ]
