# Generated by Django 4.1.1 on 2023-03-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherApp', '0002_alter_weatherlog_endtime_alter_weatherlog_starttime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherdata',
            old_name='precipitation',
            new_name='precipitation_mm',
        ),
        migrations.RemoveField(
            model_name='weatherstatistics',
            name='totalPrecipitation',
        ),
        migrations.AddField(
            model_name='weatherstatistics',
            name='totalPrecipitation_cm',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='weatherstatistics',
            name='avgMaxTemperature',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='weatherstatistics',
            name='avgMinTemperature',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
