# Generated by Django 4.1.1 on 2023-03-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherApp', '0003_rename_precipitation_weatherdata_precipitation_mm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherDataAll',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('stationID', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('maxTemperature', models.IntegerField()),
                ('minTemperature', models.IntegerField()),
                ('precipitation_mm', models.IntegerField()),
            ],
        ),
    ]
