# Generated by Django 4.1.1 on 2023-03-23 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherApp', '0004_weatherdataall'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeatherDataAll',
        ),
    ]
